apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-database
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/database/cnpg-operator/
      targetRevision: HEAD
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/database/cnpg-cluster/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
