---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: andrei@thebestpractice.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          hostedZoneName: dev-thebestpractice-tech
          project: diesel-polymer-445422-e3
          serviceAccountSecretRef:
            key: service_account.json
            name: cert-manager-dns-sa
      selector:
        dnsZones:
        - dev.thebestpractice.tech
        - '*.dev.thebestpractice.tech'
