apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo
    - repoURL: https://cloudnative-pg.github.io/charts
      path: cnpg
      chart: cloudnative-pg
      targetRevision: 0.27.1
      helm:
        releaseName: cnpg-operator
        valueFiles:
          - $valuesRepo/base/database/cnpg-operator/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true