apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - kind: Secret
      name: cilium-ca
      namespace: kube-system
      jsonPointers:
        - /data/ca.crt
        - /data/ca.key
    - kind: Secret
      name: hubble-server-certs
      namespace: kube-system
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.18.6
      helm:
        releaseName: cilium
        valueFiles:
          - $valuesRepo/base/cilium/values.yaml
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
