apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo
    - repoURL: https://charts.longhorn.io/
      chart: longhorn
      targetRevision: 1.11.0
      helm:
        releaseName: longhorn
        valueFiles:
          - $valuesRepo/base/longhorn/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
