---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: tunnel-credentials
  namespace: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-secret-store
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
  - secretKey: credentials.json
    remoteRef:
      # 1password-entry-name
      #change with the 1Password secret name for the tunnel credentials
      key: EXTSEC_1Password_k8s_cloudflare_change_me
      # 1password-document-name
      property: tunnel-credentials.json