apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cnpg-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: argo-config
  source:
    repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
    targetRevision: HEAD
    path: environments/dev/database/cnpg-cluster/clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true