---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: op-credentials
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: 1password-credentials.json
    remoteRef:
      # 1password-entry-name
      key: EXTSEC_1Password_k8s_connect_cluster
      # 1password-document-name
      property: 1password-credentials.json