apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        homelab-k8s: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-access-token
            key: token
            namespace: external-secrets