apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: 1.19.2
      path: .
      helm:
        valueFiles:
          - $valuesRepo/base/cert-manager/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
