apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo
    - repoURL: https://1password.github.io/connect-helm-charts
      targetRevision: 2.2.0
      chart: connect
      helm:
        valueFiles:
          - $valuesRepo/base/argocd/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
