apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: https://charts.external-secrets.io
      targetRevision: 1.2.1
      chart: external-secrets
      helm:
        valueFiles:
          - $valuesRepo/base/external-secrets/external-secrets/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true